# https://github.com/google-github-actions/release-please-action

name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: google-github-actions/release-please-action@514bc6cdae71484c998108f2136a8f5e4c62b9b9 # v3.7.3
        with:
          release-type: python
          version-file: pyproject.toml
          include-v-in-tag: false
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false}
            ]
          pull-request-title-pattern: "chore: release ${version}"
          release-as: "2023.2.2"
